kind: Service
apiVersion: v1
metadata:
  name: demophp
spec:
  type: LoadBalancer
  selector:
    app: demophp
  ports:
  - protocol: TCP
    port: 80

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demophp
  labels:
    app: demophp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demophp
  template:
    metadata:
      labels:
        app: demophp
    spec:
      containers:
      - name: demophp
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 80
